### PR TITLE
Add Fog Support for Azure Stack

### LINKED ISSUE #359: Bundler could not find compatible versions for gem "mime-types"
I'm trying to use the version `0.3.9` of fog-azure-rm in another project [cloud_controller_ng](https://github.com/cloudfoundry/cloud_controller_ng).
In https://github.com/cloudfoundry/cloud_controller_ng/blob/master/Gemfile#L19, `'mime-types', '~> 2.6.2'` is needed, which causes the following error.

My question is that can fog-azure-rm use a newer version of mime-types?
If so, I think, the issue is resolved.
If not, do you have any suggestions to resolve the issue?
Thanks.

```
Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 2.6.2)

  In Gemfile:
    mime-types (~> 2.6.2)

    mime-types (~> 2.6.2) x86_64-darwin-14

    mime-types (~> 2.6.2) x86_64-darwin-16

    mime-types (~> 2.6.2) x86_64-linux

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25)

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25) x86_64-darwin-14

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25) x86_64-darwin-16

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25) x86_64-linux

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

### LINKED ISSUE #367: Add Fog Support for Azure Stack
The cf cloud controller uses Fog for ARM as default for the blob store. In Fog, only endpoints for public Azure, China, US_Government and Germany are implemented, but not for Azure Stack yet.
See also storage_endpoint_suffix in https://github.com/fog/fog-azure-rm/blob/72c7dd1724368fba9f6a88d18991f6ed999dec8c/lib/fog/azurerm/utilities/general.rb#L109-L126
As a result, the storage_endpoint_suffix on Azure Stack is wrong, as it only uses the default for public Azure which is .core.windows.net. 
Please add a storage endpoint for Azure Stack.

### PR DESCRIPTION
**Pull request by bingosummer**
* Support managing storage data in Azure Stack. But it still can't create/delete storage account in Azure Stack. Fixes #367.
* Upgrade the version of mime-types gem. Fixes #359.
* Add user agent prefix in the storage requests.
* Update the dependency azure-storage.

### CODE REVIEW

**Comment by bingosummer** [comment]
@bilal-naeem-confiz Please help review. Thanks.

**Comment by WalterS** [comment]
This still references to fog-core 1.4.5, is this intentionally?

**Comment by bingosummer** [comment]
@WalterS Yes.
To resolve #367, there are two options: 1. upgrade `mime-types` itself; 2. upgrade `fog-core` to `2.0.0` so that `mime-types` can be removed.
We choose the first option, so there's no need to upgrade `fog-core`.

**Comment by WalterS** [comment]
The issue is still present. Any thoughts on how to remedy this?

**Pull request merged**
