### PR TITLE
Support multiple environments

### LINKED ISSUE #223: Different Azure cloud environment support
@abbas-sheikh-confiz storage in v0.1.1 only supports `AzureCloud`. Later we will add support for `AzureChinaCloud`, `AzureUSGovernment` and `AzureGermanCloud`. 
To keep consistent with [azure-cli](https://github.com/Azure/azure-xplat-cli/blob/bea341b53149246fb61b95883aa34b72a7e980f2/lib/util/profile/environment.js) and [azure-powershell](https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/src/Common/Commands.Common.Authentication/Models/AzureEnvironment.Methods.cs), I think we should use same names for these environments.
1. By set `environment` in `options` to use different Azure cloud environment
2. The optional values of `environment` should be one of `AzureCloud`, `AzureChinaCloud`, `AzureUSGovernment` or`AzureGermanCloud`.

So below code in this [link](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/config.rb#L26-L27) should be updated. How do you think?

```
# Set a CLOUD value from 'Azure', 'AzureChina', 'AzureGermanCloud' and 'AzureUSGovernment'
CLOUD = 'Azure'.freeze
```

### PR DESCRIPTION
**Pull request by AbelHu**
1. Add a parameter `environment` in the credential. The default value is `AzureCloud`
2. Only support multiple environments in storage in this PR
3. Close #223 
4. In guidance to get directory, `max_results` => `max_keys`: Keep same usage as AWS
5. Remove `azure_storage_connection_string` because Azure::Storage::Core::Auth::SharedAccessSignature in storage.rb only supports to use `azure_storage_account_name` and `azure_storage_access_key` so `azure_storage_access_key` is required.

### CODE REVIEW

**Comment by AbelHu** [comment]
@zeeshan-arshad-confiz We are planning to add introduction for Azure storage in fog.io but they asked us to follow [semver](http://semver.org/) [here](https://github.com/fog/fog/issues/3913#issuecomment-262548185).  Do you have any idea?

**Comment by bilal-naeem-confiz** [comment]
Hi @AbelHu ,
Please update your integration tests to use the environment parameter when creating services (storage, resources etc)
Thanks

**Comment by AbelHu** [comment]
@bilal-naeem-confiz I did not hit the warning you said. But I still update the integration tests to use `environment`. Only storage part supports the new parameter `environment`. The resource group does not support it so I guess you maybe set `environment` when using `Fog::Resources::AzureRM.new`.

**Comment by bilal-naeem-confiz** [comment]
@AbelHu why have you not implemented multiple environment support for other services? Have you tried running the integration tests?

**Pull request merged**
