### PR TITLE
Add telemetry information into fog-azure-rm to understand active usage & consumption

### PR DESCRIPTION
**Pull request by vishrutshah**
Hello All,

As part of understanding the usage and consumption of the `fog-azure-rm` and other libraries those are being built on top of [azure_mgmt_*](https://rubygems.org/search?utf8=%E2%9C%93&query=azure_mgmt_) sdks, we'd like to add fog-azure-rm gems's information (specifically name of the gem and version being used)  into our request telemetry pipeline. This initiative would allow Azure Ruby SDK Team at Microsoft to provide better active support & pursue higher priority functionalities of the Azure Resource Management services being built into [Azure/azure-sdk-for-ruby](https://github.com/Azure/azure-sdk-for-ruby). This work is being tracked at  [#517](https://github.com/Azure/azure-sdk-for-ruby/issues/517).

We'd love to have your feedbacks & views on this PR. 

Looking forwards to learning more from fog-azure-rm community. 👍 

Thanks,
Azure Ruby SDK Team

cc:
@salameer, @veronicagg, @jkwon2013, @sarangan12

### CODE REVIEW

**Comment by abbas-sheikh-confiz** [comment]
@geemus @plribeiro3000 what do you guys think about this?

**Comment by geemus** [comment]
@abbas-sheikh-confiz I don't have the most context, it looks like it is mostly setting particular user-agent info? That seems reasonable enough, though I would say a compound agent including fog version would probably be best (it may already be that way, just wasn't totally clear to me at a glance). I was less certain about the changes to certain method calls, guessing they are just updates based on the gem bump? Overall it seems alright, what do you think?

**Comment by plribeiro3000** [comment]
I don't have enough context but this seems to be safe. 
Agreed with @geemus regarding code that are not directly related to the user agent info which makes it kind of lost in the middle of the other changes but might just be a small needed changed.

👍

**Comment by vishrutshah** [comment]
Thanks @geemus, @plribeiro3000 & @abbas-sheikh-confiz  for taking time to review this changes & provide feedbacks. 

- As you noticed that there are couple of minor unrelated changes came-in with this PR as I updated versions from 0.7.0 to 0.8.0. If you prefer, I can put those changes in separate commits. 
- Secondly, this changes will updated the way we collect the telemetry information through User-Agent string to include additional information about fog client and version. Following is the sample example header that reflects the new User-Agent string for detail look with this changes:

```
    headers:
      User-Agent:
      - Ruby/2.2.4 (x86_64-darwin15) ms_rest/0.6.0 ms_rest_azure/0.6.0 Azure-SDK-For-Ruby
        azure_mgmt_network/0.7.0 fog-azure-rm/0.1.2
      Content-Type:
      - application/json; charset=utf-8
      accept-language:
      - en-US
      x-ms-client-request-id:
      - xxxxxx-xxxxxx-xxxxxx-xxxxx
```

Thanks again for taking time to review. 

Cheers,
Vishrut Shah

**Comment by geemus** [comment]
Thanks for the clarification. 👍  LGTM. I'll leave it for @abbas-sheikh-confiz to merge when ready.

**Comment by vishrutshah** [comment]
Hello @abbas-sheikh-confiz, Please let us know what are you plans and timelines to incorporate this change into fog-azure-rm. 

Due to latest check-ins into master, I've rebased my changes on top of the latest ones. I noticed some changes that I am not sure intentional/unintentional with commit [10cc5d0f912fbfadbecc013f8d45f8d1bf27823b](https://github.com/fog/fog-azure-rm/commit/10cc5d0f912fbfadbecc013f8d45f8d1bf27823b). As i am interpreting the change, one of the change is to update all azure_mgmt_* gems to version 0.8.0.

This change removes the `test_list_record_sets.rb` & `test_list_zones.rb` files. I believe that they are testing [lib/fog/azurerm/requests/dns/list_record_sets.rb](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/requests/dns/list_record_sets.rb) & [lib/fog/azurerm/requests/dns/list_zones.rb](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/requests/dns/list_zones.rb). Now I do not see the methods `list_all_in_resource_group` & `list_in_subscription` into azure_mgmt_dns version 0.8.0 in [Zones](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/zones.rb#L10) and [RecordSets](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_dns/lib/generated/azure_mgmt_dns/record_sets.rb#L10). My change is updating them to use the correct method. @waqar-haider-confiz Could you please review that change is correct with respect to 0.8.0 version of azure_mgmt_dns?. 

Awaiting your response. 

Thanks,
Vishrut Shah

**Comment by waqar-haider-confiz** [comment]
Hey @vishrutshah ,

I reviewed your changes and they sounds good. However, one unit test for DNS Zone with updated correct method is missing. Please add that unit test so that we can merge it.


Thanks

**Comment by vishrutshah** [comment]
Thanks a lot @waqar-haider-confiz for quick code review. I've added unit test for the list method of dns zones. Please let me know if any more changes are required. 

Thanks,
Vishrut Shah

**Comment by zeeshan-arshad-confiz** [comment]
Hi @vishrutshah 

Please resolve merge conflicts so we can merge it.

Thanks.

**Comment by zeeshan-arshad-confiz** [comment]
Hi @vishrutshah 

I have merged branch conflicts and pull request has been merged now.

**Pull request merged**
