### PR TITLE
Correct get blob properties mock, fixes #387.

### LINKED ISSUE #387: Storage#get_blob_properties mock is inaccurate
Hi Folks,

Thanks for taking the time to read this. I'm using fog-azure-rm to control some containers on a storage account. I'm using some fairly low-level requests such as `put_blob` and `get_blob_properties`, which I appreciate isn't always the point of fog, however the mocks are very useful indeed. I noticed that when mocking is turned on, the value returned by `get_blob_properties` in the mock class is not the same as the real class.

Here is an example:
When mocking is turned on, we see the returned object is a Hash.
```
irb(main):001:0> require 'fog/azurerm' ; Fog.mock! ; mock_fog_connection = Fog::Storage::AzureRM.new(azure_storage_account_name: "astorageaccount", azure_storage_access_key: "bm90IGEgcmVhbCBrZXkK") ; mock_fog_connection.directories.create(key: 'test-bucket') ; mock_fog_connection.directories.get('test-bucket').files.create(key: 'foo', body: File.read('/a/real/file')) ; mock_fog_connection.get_blob_properties('test-bucket', 'foo')
=> {"name"=>"test_blob", "metadata"=>{}, "properties"=>{"last_modified"=>"Mon, 04 Jul 2016 09:30:31 GMT", "etag"=>"0x8D3A3EDD7C2B777", "lease_status"=>"unlocked", "lease_state"=>"available", "lease_duration"=>nil, "content_length"=>4194304, "content_type"=>"application/octet-stream", "content_encoding"=>nil, "content_language"=>nil, "content_disposition"=>nil, "content_md5"=>"tXAohIyxuu/t94Lp/ujeRw==", "cache_control"=>nil, "sequence_number"=>0, "blob_type"=>"PageBlob", "copy_id"=>"095adc3b-e277-4c3d-97e0-0abca881f60c", "copy_status"=>"success", "copy_source"=>"https://testaccount.blob.core.windows.net/testblob/4m?snapshot=2016-02-04T08%3A35%3A50.3157696Z", "copy_progress"=>"4194304/4194304", "copy_completion_time"=>"Thu, 04 Feb 2016 08:35:52 GMT", "copy_status_description"=>nil, "accept_ranges"=>0}}
irb(main):002:0> mock_properties.class
=> Hash
```
However, when mocking is turned off, the returned object is instead an instance of Azure::Storage::Blob::Blob, as follows:
```
irb(main):001:0> require 'fog/azurerm' ; fog_connection = Fog::Storage::AzureRM.new(azure_storage_account_name: "astorageaccount", azure_storage_access_key: "bm90IGEgcmVhbCBrZXkK") ; fog_connection.get_blob_properties('test-bucket', 'foo')
=> #<Azure::Storage::Blob::Blob:0x007f896d25ee48 @properties={:last_modified=>"Mon, 14 May 2018 08:50:05 GMT", :etag=>"\"0x8D5B977B02DE917\"", :lease_status=>"unlocked", :lease_state=>"available", :lease_duration=>nil, :content_length=>166296, :content_type=>"text/plain; charset=UTF-8", :content_encoding=>nil, :content_language=>nil, :content_disposition=>nil, :content_md5=>"DJFoMkHW4AN8a3v7UfFQDw==", :cache_control=>nil, :blob_type=>"BlockBlob", :copy_id=>nil, :copy_status=>nil, :copy_source=>nil, :copy_progress=>nil, :copy_completion_time=>nil, :copy_status_description=>nil, :accept_ranges=>0}, @metadata={}, @name="foo", @snapshot=nil>
irb(main):002:0> real_properties.class
=> Azure::Storage::Blob::Blob
```

I went to implement a change to fix this mismatch, however when going to fix the tests, I noticed that Hashes underpin a lot of the testing data, and I was not too sure what to do after that. I believe if I fix the tests for this mock, then other tests will probably break if they are expecting a Hash. Given that this has started to bring up other areas of the codebase that I'm not familiar with, I was hoping that someone could give me some guidance.

Many thanks,

-- easkay

### PR DESCRIPTION
**Pull request by easkay**
Fixes #387.

Return an Azure::Storage::Blob::Blob from `get_blob_properties` instead of a Hash.

### CODE REVIEW

**Comment by easkay** [comment]
@bilal-naeem-confiz this code did not turn out as ugly as I'd expect. If you have any further feedback, I'll happily address it otherwise I think this is close to being done.

**Comment by bilal-naeem-confiz** [comment]
Hi @easkay 
I wanted to ask if this PR is complete. If it is, then I'll merge it.

**Comment by easkay** [comment]
@bilal-naeem-confiz Apologies for the confusion, yes I feel it's ready :)

**Comment by bilal-naeem-confiz** [comment]
@easkay thanks for your contribution. Really appreciate it.

**Pull request merged**
