### PR TITLE
Feature/sd 4594/snapshot destroy

### PR DESCRIPTION
**Pull request by zhitongLIU**
Hello there,
this PR is an implementation of destroy azure snapshot on fog
depends on https://github.com/fog/fog-azure-rm/pull/352

lemme know how can I improve it :)

### CODE REVIEW

**Comment by maham-nazir-confiz** [comment]
@zhitongLIU 
Hello, thank you for submitting this PR.

Can you add the functionality to create a Snapshot as well via Fog ARM? 
Please write an integration test for this as well.

**Comment by KevinLoiseau** [comment]
Hi @maham-nazir-confiz, this pull request is not ready, we was working by incrementation. I waiting https://github.com/fog/fog-azure-rm/pull/352 for populate PR about snapshot listing and getting and then the PR about creation.
@zhitongLIU may you rebase this PR on https://github.com/fog/fog-azure-rm/pull/352 for cleaning the history ?

**Comment by abbas-sheikh-confiz** [comment]
@KevinLoiseau 
Please let us know when the PR is final.
Thanks,

**Comment by KevinLoiseau** [comment]
@abbas-sheikh-confiz 
All of our PR are already ready (required a little rebase however), but based on https://github.com/fog/fog-azure-rm/pull/352 that is just a basic step without functionnallity.

Currently we have this tree :
- Snapshot model (https://github.com/fog/fog-azure-rm/pull/352) => basic step
  - Snapshot view (listing and getting)
    - Snapshot create
    - Snapshot delete

Do you want us to regroup this PRs ? Which of them ?
FYI all of them are currently used in our fork and that looks working fine.

**Comment by maham-nazir-confiz** [comment]
@KevinLoiseau 
Please create a single PR which contains functionality for 
- Create Snapshot
- Delete Snapshot
- Get Snapshot
- List Snapshots (Within a Resource Group or Subscription)

Write the appropriate unit tests and integration tests as well. Also update the documentation.
Thank you.

**Comment by bilal-naeem-confiz** [comment]
Hi @KevinLoiseau 
We are closing this PR as of now. Please generate a single PR for your feature once it is done.
Thanks

**Pull request closed without merging**
